// Auto-generated IMMUTABLE factory default — never edited at runtime (no admin in this build).
// Mirror of the Travler catalogue, loaded as a <script> so the shop reads data without
// fetch() (which browsers block on file://). Field names match the Travler build spec.
window.TRIPS_DEFAULT = [
  {
    "sku": "TRV-BCH-001",
    "image": "TRV-BCH-001.jpg",
    "image_lifestyle": "TRV-BCH-001-2.jpg",
    "name_en": "Mallorca beach escape",
    "name_nl": "Mallorca strandvakantie",
    "hotel": "Sol Bahia Palma",
    "category": "Beach holidays",
    "destination": "Mallorca",
    "country": "Spain",
    "nights": 7,
    "board": "Half board",
    "price_eur": 729,
    "sale_price_eur": 649,
    "stock": 6,
    "rating": 4,
    "popularity": 88,
    "tags": ["beach", "couples", "summer", "mediterranean"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "London Stansted", "Manchester"],
    "pairs_with": ["TRV-BCH-004", "TRV-BCH-002", "TRV-LUX-001"],
    "addonIds": ["ADD-TRANSFER", "ADD-INSURANCE", "ADD-ROOM"],
    "short_desc_en": "A relaxed half-board stay on Mallorca's sunny coast, with the beach close by and plenty of time to unwind.",
    "short_desc_nl": "Een ontspannen halfpension-verblijf aan de zonnige kust van Mallorca, met het strand dichtbij en volop tijd om te ontspannen.",
    "highlights_en": ["Short walk to the beach", "Half board included", "Popular with couples", "Warm Mediterranean summer"],
    "highlights_nl": ["Korte wandeling naar het strand", "Halfpension inbegrepen", "Populair bij koppels", "Warme mediterrane zomer"]
  },
  {
    "sku": "TRV-BCH-002",
    "image": "TRV-BCH-002.jpg",
    "image_lifestyle": "TRV-BCH-002-2.jpg",
    "name_en": "Crete all inclusive resort",
    "name_nl": "Kreta all inclusive resort",
    "hotel": "Aegean Blue Resort",
    "category": "All inclusive",
    "destination": "Crete",
    "country": "Greece",
    "nights": 7,
    "board": "All inclusive",
    "price_eur": 899,
    "sale_price_eur": 799,
    "stock": 3,
    "rating": 4,
    "popularity": 85,
    "tags": ["beach", "all inclusive", "families", "pool"],
    "lastMinute": true,
    "departureAirports": ["Amsterdam", "Eindhoven", "Manchester"],
    "pairs_with": ["TRV-BCH-003", "TRV-LH-003", "TRV-LH-002"],
    "addonIds": ["ADD-TRANSFER", "ADD-INSURANCE", "ADD-EXCURSION"],
    "short_desc_en": "An all-inclusive beach resort on Crete with a large pool, relaxed dining and everything covered for a stress-free week.",
    "short_desc_nl": "Een all inclusive strandresort op Kreta met een groot zwembad, ontspannen eten en alles geregeld voor een zorgeloze week.",
    "highlights_en": ["All inclusive board", "Large resort pool", "Great for families", "Beachfront location"],
    "highlights_nl": ["All inclusive verzorging", "Groot resortzwembad", "Ideaal voor gezinnen", "Ligging aan het strand"]
  },
  {
    "sku": "TRV-BCH-003",
    "image": "TRV-BCH-003.jpg",
    "image_lifestyle": "TRV-BCH-003-2.jpg",
    "name_en": "Antalya family resort",
    "name_nl": "Antalya familieresort",
    "hotel": "Belek Family Palace",
    "category": "Family holidays",
    "destination": "Antalya",
    "country": "Turkey",
    "nights": 10,
    "board": "All inclusive",
    "price_eur": 899,
    "sale_price_eur": null,
    "stock": 7,
    "rating": 4,
    "popularity": 78,
    "tags": ["family", "kids club", "waterpark", "value"],
    "lastMinute": true,
    "departureAirports": ["Amsterdam", "Rotterdam", "Birmingham"],
    "pairs_with": ["TRV-FAM-002", "TRV-FAM-001", "TRV-BCH-002"],
    "addonIds": ["ADD-TRANSFER", "ADD-LUGGAGE", "ADD-KIDSCLUB"],
    "short_desc_en": "Ten all-inclusive nights in Belek with a waterpark and kids' club, built around family value.",
    "short_desc_nl": "Tien nachten all inclusive in Belek met een waterpark en kids club, gericht op een voordelige gezinsvakantie.",
    "highlights_en": ["Waterpark on site", "Supervised kids' club", "10 nights all inclusive", "Great value for families"],
    "highlights_nl": ["Waterpark op locatie", "Begeleide kids club", "10 nachten all inclusive", "Uitstekende prijs-kwaliteit voor gezinnen"]
  },
  {
    "sku": "TRV-BCH-004",
    "image": "TRV-BCH-004.jpg",
    "image_lifestyle": "TRV-BCH-004-2.jpg",
    "name_en": "Tenerife winter sun",
    "name_nl": "Tenerife winterzon",
    "hotel": "Costa Adeje Sun Hotel",
    "category": "Winter sun",
    "destination": "Tenerife",
    "country": "Spain",
    "nights": 7,
    "board": "Breakfast included",
    "price_eur": 699,
    "sale_price_eur": null,
    "stock": 8,
    "rating": 4,
    "popularity": 74,
    "tags": ["winter sun", "beach", "couples", "canary islands"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "London Stansted"],
    "pairs_with": ["TRV-LH-002", "TRV-FAM-004", "TRV-BCH-001"],
    "addonIds": ["ADD-TRANSFER", "ADD-CAR", "ADD-INSURANCE"],
    "short_desc_en": "Reliable winter sun on Tenerife, with breakfast included and the beach a short stroll from the hotel.",
    "short_desc_nl": "Betrouwbare winterzon op Tenerife, met ontbijt inbegrepen en het strand op loopafstand van het hotel.",
    "highlights_en": ["Year-round mild climate", "Breakfast included", "Short stroll to the beach", "Popular with couples"],
    "highlights_nl": ["Mild klimaat het hele jaar door", "Ontbijt inbegrepen", "Korte wandeling naar het strand", "Populair bij koppels"]
  },
  {
    "sku": "TRV-CITY-001",
    "image": "TRV-CITY-001.jpg",
    "image_lifestyle": "TRV-CITY-001-2.jpg",
    "name_en": "Barcelona city break",
    "name_nl": "Barcelona stedentrip",
    "hotel": "Hotel Eixample Central",
    "category": "City breaks",
    "destination": "Barcelona",
    "country": "Spain",
    "nights": 4,
    "board": "Room only",
    "price_eur": 459,
    "sale_price_eur": 399,
    "stock": 4,
    "rating": 4,
    "popularity": 92,
    "tags": ["city", "culture", "weekend", "couples", "city centre"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Eindhoven", "Bristol"],
    "pairs_with": ["TRV-CITY-003", "TRV-CITY-002", "TRV-CITY-004"],
    "addonIds": ["ADD-TRANSFER", "ADD-TOUR", "ADD-INSURANCE"],
    "short_desc_en": "A four-night city break in central Barcelona, close to the sights, tapas bars and architecture the city is known for.",
    "short_desc_nl": "Een stedentrip van vier nachten in het centrum van Barcelona, dicht bij de bezienswaardigheden, tapasbars en architectuur waar de stad om bekendstaat.",
    "highlights_en": ["Central Eixample location", "Walkable to major sights", "Room-only flexibility", "Ideal for a long weekend"],
    "highlights_nl": ["Centrale ligging in Eixample", "Loopafstand tot grote bezienswaardigheden", "Flexibel met logies only", "Ideaal voor een lang weekend"]
  },
  {
    "sku": "TRV-CITY-002",
    "image": "TRV-CITY-002.jpg",
    "image_lifestyle": "TRV-CITY-002-2.jpg",
    "name_en": "Lisbon weekend escape",
    "name_nl": "Lissabon weekendtrip",
    "hotel": "Baixa Riverside Hotel",
    "category": "City breaks",
    "destination": "Lisbon",
    "country": "Portugal",
    "nights": 3,
    "board": "Breakfast included",
    "price_eur": 359,
    "sale_price_eur": null,
    "stock": 5,
    "rating": 4,
    "popularity": 80,
    "tags": ["city", "food", "weekend", "culture"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Rotterdam"],
    "pairs_with": ["TRV-CITY-001", "TRV-CITY-003", "TRV-LH-004"],
    "addonIds": ["ADD-TOUR", "ADD-TRANSFER"],
    "short_desc_en": "A short break in riverside Lisbon, with breakfast included and easy access to the old town's food and culture.",
    "short_desc_nl": "Een korte break in Lissabon aan de rivier, met ontbijt inbegrepen en eenvoudige toegang tot de eet- en cultuurscene van de oude stad.",
    "highlights_en": ["Riverside Baixa location", "Breakfast included", "Great for food lovers", "Compact three-night format"],
    "highlights_nl": ["Ligging aan de rivier in Baixa", "Ontbijt inbegrepen", "Ideaal voor foodliefhebbers", "Compact verblijf van drie nachten"]
  },
  {
    "sku": "TRV-CITY-003",
    "image": "TRV-CITY-003.jpg",
    "image_lifestyle": "TRV-CITY-003-2.jpg",
    "name_en": "Rome culture trip",
    "name_nl": "Rome cultuurreis",
    "hotel": "Hotel Trastevere Roma",
    "category": "City breaks",
    "destination": "Rome",
    "country": "Italy",
    "nights": 4,
    "board": "Breakfast included",
    "price_eur": 449,
    "sale_price_eur": null,
    "stock": 7,
    "rating": 5,
    "popularity": 82,
    "tags": ["city", "culture", "history", "couples", "city centre"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "London Stansted", "Birmingham"],
    "pairs_with": ["TRV-CITY-001", "TRV-CITY-002", "TRV-CITY-004"],
    "addonIds": ["ADD-TOUR", "ADD-TRANSFER"],
    "short_desc_en": "Four nights in charming Trastevere, walking distance from Rome's historic centre and its landmark sights.",
    "short_desc_nl": "Vier nachten in het sfeervolle Trastevere, op loopafstand van het historische centrum van Rome en de bekende bezienswaardigheden.",
    "highlights_en": ["Highly rated hotel", "Walkable historic centre", "Breakfast included", "Popular with couples"],
    "highlights_nl": ["Hoog gewaardeerd hotel", "Historisch centrum op loopafstand", "Ontbijt inbegrepen", "Populair bij koppels"]
  },
  {
    "sku": "TRV-CITY-004",
    "image": "TRV-CITY-004.jpg",
    "image_lifestyle": "TRV-CITY-004-2.jpg",
    "name_en": "Prague winter city break",
    "name_nl": "Praag stedentrip in de winter",
    "hotel": "Old Town Vltava Hotel",
    "category": "City breaks",
    "destination": "Prague",
    "country": "Czech Republic",
    "nights": 3,
    "board": "Room only",
    "price_eur": 389,
    "sale_price_eur": 329,
    "stock": 9,
    "rating": 3,
    "popularity": 70,
    "tags": ["city", "winter", "value", "weekend"],
    "lastMinute": false,
    "departureAirports": ["Eindhoven", "Amsterdam"],
    "pairs_with": ["TRV-CITY-003", "TRV-CITY-002", "TRV-CITY-001"],
    "addonIds": ["ADD-TRANSFER", "ADD-TOUR"],
    "short_desc_en": "A good-value winter city break in Prague's old town, ideal for a short trip on a budget.",
    "short_desc_nl": "Een voordelige winterse stedentrip in de oude binnenstad van Praag, ideaal voor een korte trip met een budget.",
    "highlights_en": ["Old town location", "Good value for money", "Compact weekend format", "Atmospheric winter city"],
    "highlights_nl": ["Ligging in de oude binnenstad", "Goede prijs-kwaliteitverhouding", "Compact weekendformat", "Sfeervolle winterstad"]
  },
  {
    "sku": "TRV-FAM-001",
    "image": "TRV-FAM-001.jpg",
    "image_lifestyle": "TRV-FAM-001-2.jpg",
    "name_en": "Costa Dorada family park",
    "name_nl": "Costa Dorada familiepark",
    "hotel": "Dorada Parkside Hotel",
    "category": "Family holidays",
    "destination": "Costa Dorada",
    "country": "Spain",
    "nights": 7,
    "board": "Half board",
    "price_eur": 749,
    "sale_price_eur": null,
    "stock": 5,
    "rating": 4,
    "popularity": 76,
    "tags": ["family", "theme park", "beach", "kids"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Rotterdam", "Manchester"],
    "pairs_with": ["TRV-FAM-003", "TRV-FAM-004", "TRV-BCH-003"],
    "addonIds": ["ADD-PARK", "ADD-TRANSFER", "ADD-INSURANCE"],
    "short_desc_en": "A half-board family week on Costa Dorada, close to the beach and within easy reach of the region's theme parks.",
    "short_desc_nl": "Een gezinsweek met halfpension aan de Costa Dorada, dicht bij het strand en op korte afstand van de pretparken in de regio.",
    "highlights_en": ["Close to theme parks", "Half board included", "Family-friendly hotel", "Beach nearby"],
    "highlights_nl": ["Dicht bij pretparken", "Halfpension inbegrepen", "Gezinsvriendelijk hotel", "Strand in de buurt"]
  },
  {
    "sku": "TRV-FAM-002",
    "image": "TRV-FAM-002.jpg",
    "image_lifestyle": "TRV-FAM-002-2.jpg",
    "name_en": "Rhodes kids club resort",
    "name_nl": "Rhodos kids club resort",
    "hotel": "Faliraki Kids Resort",
    "category": "Family holidays",
    "destination": "Rhodes",
    "country": "Greece",
    "nights": 7,
    "board": "All inclusive",
    "price_eur": 849,
    "sale_price_eur": null,
    "stock": 4,
    "rating": 4,
    "popularity": 79,
    "tags": ["family", "kids club", "beach", "pool"],
    "lastMinute": true,
    "departureAirports": ["Amsterdam", "Birmingham"],
    "pairs_with": ["TRV-FAM-001", "TRV-BCH-003", "TRV-FAM-004"],
    "addonIds": ["ADD-KIDSCLUB", "ADD-TRANSFER"],
    "short_desc_en": "An all-inclusive family resort in Faliraki with a supervised kids' club and a beachfront pool.",
    "short_desc_nl": "Een all inclusive familieresort in Faliraki met een begeleide kids club en een zwembad aan het strand.",
    "highlights_en": ["Supervised kids' club", "All inclusive board", "Beachfront pool", "Popular family choice"],
    "highlights_nl": ["Begeleide kids club", "All inclusive verzorging", "Zwembad aan het strand", "Populaire keuze voor gezinnen"]
  },
  {
    "sku": "TRV-FAM-003",
    "image": "TRV-FAM-003.jpg",
    "image_lifestyle": "TRV-FAM-003-2.jpg",
    "name_en": "Algarve family apartments",
    "name_nl": "Algarve familie-appartementen",
    "hotel": "Albufeira Garden Apartments",
    "category": "Family holidays",
    "destination": "Algarve",
    "country": "Portugal",
    "nights": 7,
    "board": "Self catering",
    "price_eur": 679,
    "sale_price_eur": 599,
    "stock": 10,
    "rating": 3,
    "popularity": 68,
    "tags": ["family", "apartments", "beach", "value"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Eindhoven", "Bristol"],
    "pairs_with": ["TRV-FAM-001", "TRV-FAM-004", "TRV-BCH-001"],
    "addonIds": ["ADD-CAR", "ADD-INSURANCE", "ADD-BREAKFAST"],
    "short_desc_en": "Self-catering garden apartments in Albufeira, a relaxed and affordable base for a family week near the beach.",
    "short_desc_nl": "Zelfverzorgende tuinappartementen in Albufeira, een ontspannen en betaalbare uitvalsbasis voor een gezinsweek bij het strand.",
    "highlights_en": ["Self-catering flexibility", "Family-sized apartments", "Good value for money", "Beach within reach"],
    "highlights_nl": ["Flexibiliteit met zelfverzorging", "Appartementen geschikt voor gezinnen", "Goede prijs-kwaliteitverhouding", "Strand binnen bereik"]
  },
  {
    "sku": "TRV-FAM-004",
    "image": "TRV-FAM-004.jpg",
    "image_lifestyle": "TRV-FAM-004-2.jpg",
    "name_en": "Gran Canaria family sun",
    "name_nl": "Gran Canaria familiezon",
    "hotel": "Maspalomas Dunes Hotel",
    "category": "Family holidays",
    "destination": "Gran Canaria",
    "country": "Spain",
    "nights": 7,
    "board": "Half board",
    "price_eur": 719,
    "sale_price_eur": null,
    "stock": 6,
    "rating": 4,
    "popularity": 66,
    "tags": ["family", "winter sun", "beach", "pool"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "London Stansted"],
    "pairs_with": ["TRV-BCH-004", "TRV-FAM-003", "TRV-FAM-002"],
    "addonIds": ["ADD-TRANSFER", "ADD-ROOM"],
    "short_desc_en": "A half-board family stay near the Maspalomas dunes, with reliable sun, a pool and the beach close by.",
    "short_desc_nl": "Een gezinsverblijf met halfpension bij de duinen van Maspalomas, met betrouwbare zon, een zwembad en het strand dichtbij.",
    "highlights_en": ["Near the Maspalomas dunes", "Half board included", "Reliable year-round sun", "Family-friendly pool"],
    "highlights_nl": ["Bij de duinen van Maspalomas", "Halfpension inbegrepen", "Betrouwbare zon het hele jaar", "Gezinsvriendelijk zwembad"]
  },
  {
    "sku": "TRV-LUX-001",
    "image": "TRV-LUX-001.jpg",
    "image_lifestyle": "TRV-LUX-001-2.jpg",
    "name_en": "Santorini adults only escape",
    "name_nl": "Santorini adults only vakantie",
    "hotel": "Oia Cliffside Suites",
    "category": "Luxury escapes",
    "destination": "Santorini",
    "country": "Greece",
    "nights": 5,
    "board": "Breakfast included",
    "price_eur": 1349,
    "sale_price_eur": 1199,
    "stock": 2,
    "rating": 5,
    "popularity": 90,
    "tags": ["luxury", "adults only", "couples", "sea view"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "London Stansted"],
    "pairs_with": ["TRV-LUX-003", "TRV-LUX-002", "TRV-LUX-004"],
    "addonIds": ["ADD-TRANSFER", "ADD-ROOM", "ADD-LOUNGE"],
    "short_desc_en": "Adults-only cliffside suites in Oia with sweeping sea views, built for a quiet luxury escape.",
    "short_desc_nl": "Adults only cliffside suites in Oia met weids zeezicht, gemaakt voor een rustige luxe ontsnapping.",
    "highlights_en": ["Adults-only property", "Cliffside sea views", "Breakfast included", "Five-star rated"],
    "highlights_nl": ["Adults only accommodatie", "Cliffside met zeezicht", "Ontbijt inbegrepen", "Vijf sterren beoordeling"]
  },
  {
    "sku": "TRV-LUX-002",
    "image": "TRV-LUX-002.jpg",
    "image_lifestyle": "TRV-LUX-002-2.jpg",
    "name_en": "Madeira boutique hotel",
    "name_nl": "Madeira boutiquehotel",
    "hotel": "Funchal Boutique Lodge",
    "category": "Luxury escapes",
    "destination": "Madeira",
    "country": "Portugal",
    "nights": 7,
    "board": "Breakfast included",
    "price_eur": 999,
    "sale_price_eur": null,
    "stock": 7,
    "rating": 5,
    "popularity": 64,
    "tags": ["boutique", "hiking", "couples", "island"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Rotterdam"],
    "pairs_with": ["TRV-ACT-004", "TRV-LUX-003", "TRV-LUX-001"],
    "addonIds": ["ADD-CAR", "ADD-EXCURSION", "ADD-INSURANCE"],
    "short_desc_en": "A boutique week in Funchal, pairing comfortable island luxury with Madeira's hiking trails on the doorstep.",
    "short_desc_nl": "Een boutiqueweek in Funchal, waarbij comfortabele eilandluxe wordt gecombineerd met de wandelpaden van Madeira voor de deur.",
    "highlights_en": ["Boutique-style lodge", "Breakfast included", "Close to hiking trails", "Five-star rated"],
    "highlights_nl": ["Boutique-lodge", "Ontbijt inbegrepen", "Dicht bij wandelroutes", "Vijf sterren beoordeling"]
  },
  {
    "sku": "TRV-LUX-003",
    "image": "TRV-LUX-003.jpg",
    "image_lifestyle": "TRV-LUX-003-2.jpg",
    "name_en": "Dubrovnik sea view escape",
    "name_nl": "Dubrovnik met zeezicht",
    "hotel": "Adriatic View Hotel",
    "category": "Luxury escapes",
    "destination": "Dubrovnik",
    "country": "Croatia",
    "nights": 5,
    "board": "Half board",
    "price_eur": 1049,
    "sale_price_eur": null,
    "stock": 5,
    "rating": 5,
    "popularity": 72,
    "tags": ["luxury", "sea view", "culture", "couples"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Manchester"],
    "pairs_with": ["TRV-LUX-001", "TRV-LUX-004", "TRV-LUX-002"],
    "addonIds": ["ADD-TRANSFER", "ADD-TOUR"],
    "short_desc_en": "A five-night half-board escape overlooking the Adriatic, combining Dubrovnik's old town with sea-view comfort.",
    "short_desc_nl": "Een ontsnapping van vijf nachten met halfpension en uitzicht op de Adriatische Zee, waarbij de oude binnenstad van Dubrovnik wordt gecombineerd met comfort en zeezicht.",
    "highlights_en": ["Sea-view rooms", "Half board included", "Walkable old town", "Five-star rated"],
    "highlights_nl": ["Kamers met zeezicht", "Halfpension inbegrepen", "Oude binnenstad op loopafstand", "Vijf sterren beoordeling"]
  },
  {
    "sku": "TRV-LUX-004",
    "image": "TRV-LUX-004.jpg",
    "image_lifestyle": "TRV-LUX-004-2.jpg",
    "name_en": "Bodrum spa resort",
    "name_nl": "Bodrum spa resort",
    "hotel": "Aegean Spa Resort",
    "category": "Luxury escapes",
    "destination": "Bodrum",
    "country": "Turkey",
    "nights": 7,
    "board": "All inclusive",
    "price_eur": 1099,
    "sale_price_eur": null,
    "stock": 6,
    "rating": 5,
    "popularity": 61,
    "tags": ["spa", "luxury", "adults only", "beach"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Birmingham"],
    "pairs_with": ["TRV-LUX-001", "TRV-LUX-003", "TRV-BCH-002"],
    "addonIds": ["ADD-SPA", "ADD-TRANSFER"],
    "short_desc_en": "An adults-only all-inclusive spa resort on the Aegean coast, built around relaxation and beachfront comfort.",
    "short_desc_nl": "Een all inclusive spa-resort voor volwassenen aan de Egeïsche kust, gebouwd rond ontspanning en comfort aan het strand.",
    "highlights_en": ["Adults-only resort", "All inclusive board", "On-site spa", "Beachfront setting"],
    "highlights_nl": ["Resort voor volwassenen", "All inclusive verzorging", "Spa op locatie", "Ligging aan het strand"]
  },
  {
    "sku": "TRV-LH-001",
    "image": "TRV-LH-001.jpg",
    "image_lifestyle": "TRV-LH-001-2.jpg",
    "name_en": "Curacao beach holiday",
    "name_nl": "Curacao strandvakantie",
    "hotel": "Willemstad Beach Resort",
    "category": "Beach holidays",
    "destination": "Curacao",
    "country": "Curacao",
    "nights": 9,
    "board": "Breakfast included",
    "price_eur": 1299,
    "sale_price_eur": null,
    "stock": 4,
    "rating": 4,
    "popularity": 58,
    "tags": ["long haul", "beach", "caribbean", "diving"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam"],
    "pairs_with": ["TRV-LH-002", "TRV-LH-003", "TRV-BCH-001"],
    "addonIds": ["ADD-INSURANCE", "ADD-CAR", "ADD-EXCURSION"],
    "short_desc_en": "Nine nights on Curacao's Caribbean coast, with breakfast included and some of the region's best diving nearby.",
    "short_desc_nl": "Negen nachten aan de Caribische kust van Curacao, met ontbijt inbegrepen en enkele van de beste duikplekken van de regio dichtbij.",
    "highlights_en": ["Nine-night long-haul stay", "Breakfast included", "Excellent diving nearby", "Caribbean beach setting"],
    "highlights_nl": ["Negen nachten verre bestemming", "Ontbijt inbegrepen", "Uitstekende duikmogelijkheden dichtbij", "Caribisch strand"]
  },
  {
    "sku": "TRV-LH-002",
    "image": "TRV-LH-002.jpg",
    "image_lifestyle": "TRV-LH-002-2.jpg",
    "name_en": "Cape Verde island escape",
    "name_nl": "Kaapverdie eilandvakantie",
    "hotel": "Sal Island All Inclusive",
    "category": "Winter sun",
    "destination": "Sal",
    "country": "Cape Verde",
    "nights": 7,
    "board": "All inclusive",
    "price_eur": 999,
    "sale_price_eur": 899,
    "stock": 3,
    "rating": 4,
    "popularity": 77,
    "tags": ["long haul", "winter sun", "beach", "island"],
    "lastMinute": true,
    "departureAirports": ["Amsterdam", "London Stansted"],
    "pairs_with": ["TRV-BCH-004", "TRV-LH-001", "TRV-LH-003"],
    "addonIds": ["ADD-TRANSFER", "ADD-ROOM"],
    "short_desc_en": "An all-inclusive island escape on Sal, trading a long winter for guaranteed sun and beach time.",
    "short_desc_nl": "Een all inclusive eilandvakantie op Sal, waarbij een lange winter wordt ingeruild voor gegarandeerde zon en strand.",
    "highlights_en": ["Guaranteed winter sun", "All inclusive board", "Island beach setting", "Good for a last-minute break"],
    "highlights_nl": ["Gegarandeerde winterzon", "All inclusive verzorging", "Strand op een eiland", "Geschikt voor een last-minute break"]
  },
  {
    "sku": "TRV-LH-003",
    "image": "TRV-LH-003.jpg",
    "image_lifestyle": "TRV-LH-003-2.jpg",
    "name_en": "Hurghada Red Sea resort",
    "name_nl": "Hurghada Rode Zee resort",
    "hotel": "Red Sea Coral Resort",
    "category": "All inclusive",
    "destination": "Hurghada",
    "country": "Egypt",
    "nights": 7,
    "board": "All inclusive",
    "price_eur": 849,
    "sale_price_eur": 749,
    "stock": 8,
    "rating": 3,
    "popularity": 73,
    "tags": ["diving", "all inclusive", "beach", "winter sun"],
    "lastMinute": true,
    "departureAirports": ["Amsterdam", "Manchester", "Birmingham"],
    "pairs_with": ["TRV-BCH-002", "TRV-LH-002", "TRV-LH-001"],
    "addonIds": ["ADD-EXCURSION", "ADD-TRANSFER", "ADD-INSURANCE"],
    "short_desc_en": "A well-priced all-inclusive week on the Red Sea, popular with divers and winter-sun seekers alike.",
    "short_desc_nl": "Een voordelige all inclusive week aan de Rode Zee, populair bij duikers en liefhebbers van winterzon.",
    "highlights_en": ["All inclusive board", "Renowned Red Sea diving", "Reliable winter sun", "Good value for money"],
    "highlights_nl": ["All inclusive verzorging", "Bekende duikspots in de Rode Zee", "Betrouwbare winterzon", "Goede prijs-kwaliteitverhouding"]
  },
  {
    "sku": "TRV-LH-004",
    "image": "TRV-LH-004.jpg",
    "image_lifestyle": "TRV-LH-004-2.jpg",
    "name_en": "Marrakech riad break",
    "name_nl": "Marrakech riad-trip",
    "hotel": "Riad Medina Retreat",
    "category": "City breaks",
    "destination": "Marrakech",
    "country": "Morocco",
    "nights": 4,
    "board": "Breakfast included",
    "price_eur": 499,
    "sale_price_eur": null,
    "stock": 6,
    "rating": 4,
    "popularity": 69,
    "tags": ["city", "culture", "food", "short break"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Eindhoven"],
    "pairs_with": ["TRV-CITY-002", "TRV-CITY-001", "TRV-CITY-003"],
    "addonIds": ["ADD-TOUR", "ADD-TRANSFER"],
    "short_desc_en": "A short break in a traditional riad in Marrakech's medina, close to the souks and the city's food scene.",
    "short_desc_nl": "Een korte break in een traditionele riad in de medina van Marrakech, dicht bij de soeks en de foodscene van de stad.",
    "highlights_en": ["Traditional riad stay", "Breakfast included", "Walkable medina location", "Great for food and culture"],
    "highlights_nl": ["Verblijf in een traditionele riad", "Ontbijt inbegrepen", "Medina op loopafstand", "Ideaal voor eten en cultuur"]
  },
  {
    "sku": "TRV-ACT-001",
    "image": "TRV-ACT-001.jpg",
    "image_lifestyle": "TRV-ACT-001-2.jpg",
    "name_en": "Iceland northern lights",
    "name_nl": "IJsland noorderlicht",
    "hotel": "Reykjavik Aurora Hotel",
    "category": "Adventure holidays",
    "destination": "Reykjavik",
    "country": "Iceland",
    "nights": 4,
    "board": "Breakfast included",
    "price_eur": 899,
    "sale_price_eur": null,
    "stock": 3,
    "rating": 4,
    "popularity": 86,
    "tags": ["adventure", "winter", "northern lights", "couples"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "London Stansted"],
    "pairs_with": ["TRV-ACT-002", "TRV-ACT-004", "TRV-ACT-003"],
    "addonIds": ["ADD-EXCURSION", "ADD-INSURANCE"],
    "short_desc_en": "A four-night winter break chasing the northern lights, based in Reykjavik with breakfast included.",
    "short_desc_nl": "Een winterse break van vier nachten op zoek naar het noorderlicht, met Reykjavik als uitvalsbasis en ontbijt inbegrepen.",
    "highlights_en": ["Northern lights season", "Breakfast included", "Reykjavik city base", "Popular with couples"],
    "highlights_nl": ["Seizoen van het noorderlicht", "Ontbijt inbegrepen", "Uitvalsbasis Reykjavik", "Populair bij koppels"]
  },
  {
    "sku": "TRV-ACT-002",
    "image": "TRV-ACT-002.jpg",
    "image_lifestyle": "TRV-ACT-002-2.jpg",
    "name_en": "Lapland family adventure",
    "name_nl": "Lapland familieavontuur",
    "hotel": "Rovaniemi Snow Lodge",
    "category": "Adventure holidays",
    "destination": "Lapland",
    "country": "Finland",
    "nights": 5,
    "board": "Half board",
    "price_eur": 1399,
    "sale_price_eur": null,
    "stock": 4,
    "rating": 5,
    "popularity": 83,
    "tags": ["family", "snow", "winter", "adventure"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Rotterdam"],
    "pairs_with": ["TRV-ACT-001", "TRV-ACT-003", "TRV-FAM-002"],
    "addonIds": ["ADD-EXCURSION", "ADD-EQUIPMENT", "ADD-INSURANCE"],
    "short_desc_en": "A snowy family adventure in Rovaniemi, with half board and easy access to winter activities.",
    "short_desc_nl": "Een besneeuwd gezinsavontuur in Rovaniemi, met halfpension en eenvoudige toegang tot winteractiviteiten.",
    "highlights_en": ["Snow Lodge setting", "Half board included", "Family-friendly activities", "Five-star rated"],
    "highlights_nl": ["Verblijf in een Snow Lodge", "Halfpension inbegrepen", "Gezinsvriendelijke activiteiten", "Vijf sterren beoordeling"]
  },
  {
    "sku": "TRV-ACT-003",
    "image": "TRV-ACT-003.jpg",
    "image_lifestyle": "TRV-ACT-003-2.jpg",
    "name_en": "Val Thorens ski week",
    "name_nl": "Val Thorens skiweek",
    "hotel": "Les 3 Vallees Apartments",
    "category": "Ski holidays",
    "destination": "Val Thorens",
    "country": "France",
    "nights": 7,
    "board": "Self catering",
    "price_eur": 1129,
    "sale_price_eur": 999,
    "stock": 5,
    "rating": 4,
    "popularity": 75,
    "tags": ["ski", "snow", "active", "groups"],
    "lastMinute": true,
    "departureAirports": ["Amsterdam", "Eindhoven", "Bristol"],
    "pairs_with": ["TRV-ACT-002", "TRV-ACT-001", "TRV-ACT-004"],
    "addonIds": ["ADD-SKI", "ADD-EQUIPMENT", "ADD-TRANSFER"],
    "short_desc_en": "A self-catering ski week in Val Thorens, well suited to groups wanting direct access to the slopes.",
    "short_desc_nl": "Een zelfverzorgende skiweek in Val Thorens, goed geschikt voor groepen die direct toegang tot de piste willen.",
    "highlights_en": ["Self-catering apartments", "Direct piste access", "Good for groups", "Popular last-minute ski deal"],
    "highlights_nl": ["Zelfverzorgende appartementen", "Directe toegang tot de piste", "Geschikt voor groepen", "Populaire last-minute skideal"]
  },
  {
    "sku": "TRV-ACT-004",
    "image": "TRV-ACT-004.jpg",
    "image_lifestyle": "TRV-ACT-004-2.jpg",
    "name_en": "Madeira hiking holiday",
    "name_nl": "Madeira wandelvakantie",
    "hotel": "Levada Trail Lodge",
    "category": "Adventure holidays",
    "destination": "Madeira",
    "country": "Portugal",
    "nights": 7,
    "board": "Breakfast included",
    "price_eur": 849,
    "sale_price_eur": null,
    "stock": 9,
    "rating": 4,
    "popularity": 60,
    "tags": ["hiking", "nature", "active", "couples"],
    "lastMinute": false,
    "departureAirports": ["Amsterdam", "Manchester"],
    "pairs_with": ["TRV-LUX-002", "TRV-ACT-001", "TRV-ACT-003"],
    "addonIds": ["ADD-EXCURSION", "ADD-CAR", "ADD-INSURANCE"],
    "short_desc_en": "A week of levada walks and coastal scenery on Madeira, with breakfast included at a trail-side lodge.",
    "short_desc_nl": "Een week levada-wandelingen en kustlandschap op Madeira, met ontbijt inbegrepen in een lodge langs de wandelroutes.",
    "highlights_en": ["Levada hiking trails", "Breakfast included", "Scenic island setting", "Popular with couples"],
    "highlights_nl": ["Levada-wandelroutes", "Ontbijt inbegrepen", "Schilderachtig eilandlandschap", "Populair bij koppels"]
  }
];
